version: '3.8'

services:
  # Base de donn√©es MongoDB
  mongodb:
    image: mongo:8.2.4
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12341234
      - MONGO_INITDB_DATABASE=todo_db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u root -p 12341234 --authenticationDatabase admin --eval \"db.runCommand({ ping: 1 }).ok\" | grep 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  # API Flask
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://root:12341234@mongodb:27017/todo_db?authSource=admin

  # Application Angular
  frontend:
    build: ./frontend
    container_name: angular_frontend
    ports:
      - "80:80"
    depends_on:
      - backend